// <auto-generated />
namespace A2A.MC.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class JournalExport : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(JournalExport));
        
        string IMigrationMetadata.Id
        {
            get { return "202102271633416_JournalExport"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
