//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A2A.BasicCore.Service.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
  ""defaultData"": ""default data"",
  ""restrictedIntervals"": [
    {
      ""startDay"": ""Monday"",
      ""endDay"": ""Wednesday"",
      ""startTime"": ""06:00"",
      ""endTime"": ""19:00"",
      ""restrictedData"": ""restricted data 1""
    },
    {
      ""startDay"": ""Thursday"",
      ""endDay"": ""Friday"",
      ""startTime"": ""06:00"",
      ""endTime"": ""19:00"",
      ""restrictedData"": ""restricted data 2""
    }
  ]
}")]
        public string SchedulerDataJson {
            get {
                return ((string)(this["SchedulerDataJson"]));
            }
        }
    }
}
